export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          role: 'super_admin' | 'moderator' | 'support';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          role?: 'super_admin' | 'moderator' | 'support';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          role?: 'super_admin' | 'moderator' | 'support';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      cars: {
        Row: {
          id: string;
          make: string;
          model: string;
          year: number;
          price: number;
          mileage: number;
          fuel_type: string;
          transmission: string;
          description: string;
          location: string;
          seller_id: string;
          is_active: boolean;
          classification: string;
          images: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          make: string;
          model: string;
          year: number;
          price: number;
          mileage: number;
          fuel_type: string;
          transmission: string;
          description: string;
          location: string;
          seller_id: string;
          is_active?: boolean;
          classification: string;
          images?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          make?: string;
          model?: string;
          year?: number;
          price?: number;
          mileage?: number;
          fuel_type?: string;
          transmission?: string;
          description?: string;
          location?: string;
          seller_id?: string;
          is_active?: boolean;
          classification?: string;
          images?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          username: string;
          phone: string;
          profile_picture_url: string | null;
          role: string;
          is_active: boolean;
          last_login: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string;
          username: string;
          phone: string;
          profile_picture_url?: string | null;
          role?: string;
          is_active?: boolean;
          last_login?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          username?: string;
          phone?: string;
          profile_picture_url?: string | null;
          role?: string;
          is_active?: boolean;
          last_login?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          user_id: string;
          total_amount: number;
          status: string;
          payment_method: string;
          payment_status: string;
          shipping_address: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          total_amount: number;
          status?: string;
          payment_method: string;
          payment_status?: string;
          shipping_address?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          total_amount?: number;
          status?: string;
          payment_method?: string;
          payment_status?: string;
          shipping_address?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          product_type: string;
          product_name: string;
          price: number;
          quantity: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id: string;
          product_type: string;
          product_name: string;
          price: number;
          quantity: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string;
          product_type?: string;
          product_name?: string;
          price?: number;
          quantity?: number;
          created_at?: string;
        };
      };
      inquiries: {
        Row: {
          id: string;
          car_id: string;
          inquirer_id: string;
          seller_id: string;
          message: string;
          phone_number: string | null;
          email: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          inquirer_id: string;
          seller_id: string;
          message: string;
          phone_number?: string | null;
          email?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          inquirer_id?: string;
          seller_id?: string;
          message?: string;
          phone_number?: string | null;
          email?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tire_products: {
        Row: {
          id: string;
          name: string;
          brand: string;
          size: string | null;
          price: number;
          rating: number;
          sales_count: number;
          description: string | null;
          image_url: string | null;
          in_stock: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          brand: string;
          size?: string | null;
          price: number;
          rating?: number;
          sales_count?: number;
          description?: string | null;
          image_url?: string | null;
          in_stock?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          brand?: string;
          size?: string | null;
          price?: number;
          rating?: number;
          sales_count?: number;
          description?: string | null;
          image_url?: string | null;
          in_stock?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      battery_products: {
        Row: {
          id: string;
          name: string;
          brand: string;
          type: string | null;
          cca: number | null;
          price: number;
          rating: number;
          sales_count: number;
          description: string | null;
          image_url: string | null;
          in_stock: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          brand: string;
          type?: string | null;
          cca?: number | null;
          price: number;
          rating?: number;
          sales_count?: number;
          description?: string | null;
          image_url?: string | null;
          in_stock?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          brand?: string;
          type?: string | null;
          cca?: number | null;
          price?: number;
          rating?: number;
          sales_count?: number;
          description?: string | null;
          image_url?: string | null;
          in_stock?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: 'inquiry' | 'appointment' | 'system' | 'promotion' | 'order';
          read: boolean;
          data: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          type: 'inquiry' | 'appointment' | 'system' | 'promotion' | 'order';
          read?: boolean;
          data?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: 'inquiry' | 'appointment' | 'system' | 'promotion' | 'order';
          read?: boolean;
          data?: any;
          created_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          car_id: string;
          user_id: string;
          date: string;
          time: string;
          status: 'scheduled' | 'completed' | 'cancelled';
          notes: string | null;
          service_type: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          user_id: string;
          date: string;
          time: string;
          status?: 'scheduled' | 'completed' | 'cancelled';
          notes?: string | null;
          service_type: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          user_id?: string;
          date?: string;
          time?: string;
          status?: 'scheduled' | 'completed' | 'cancelled';
          notes?: string | null;
          service_type?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      admin_settings: {
        Row: {
          id: string;
          setting_key: string;
          setting_value: any;
          setting_type: 'string' | 'number' | 'boolean' | 'json';
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          setting_key: string;
          setting_value: any;
          setting_type: 'string' | 'number' | 'boolean' | 'json';
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          setting_key?: string;
          setting_value?: any;
          setting_type?: 'string' | 'number' | 'boolean' | 'json';
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      forum_topics: {
        Row: {
          id: string;
          title: string;
          content: string;
          user_id: string;
          author_name: string | null;
          category: string;
          likes: number;
          comments: number;
          created_at: string;
          updated_at: string;
          is_pinned: boolean | null;
          is_locked: boolean | null;
          views_count: number | null;
        };
        Insert: {
          id?: string;
          title: string;
          content: string;
          user_id: string;
          author_name?: string | null;
          category?: string;
          likes?: number;
          comments?: number;
          created_at?: string;
          updated_at?: string;
          is_pinned?: boolean | null;
          is_locked?: boolean | null;
          views_count?: number | null;
        };
        Update: {
          id?: string;
          title?: string;
          content?: string;
          user_id?: string;
          author_name?: string | null;
          category?: string;
          likes?: number;
          comments?: number;
          created_at?: string;
          updated_at?: string;
          is_pinned?: boolean | null;
          is_locked?: boolean | null;
          views_count?: number | null;
        };
      };
      forum_replies: {
        Row: {
          id: string;
          topic_id: string;
          content: string;
          user_id: string;
          author_name: string | null;
          likes: number;
          dislikes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          topic_id: string;
          content: string;
          user_id: string;
          author_name?: string | null;
          likes?: number;
          dislikes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          topic_id?: string;
          content?: string;
          user_id?: string;
          author_name?: string | null;
          likes?: number;
          dislikes?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      service_providers: {
        Row: {
          id: string;
          user_id: string | null;
          business_name: string;
          service_type: 'mechanic' | 'breakdown' | 'towing' | 'detailing' | 'inspection' | 'other';
          description: string | null;
          phone: string;
          email: string | null;
          address: string | null;
          location_lat: number | null;
          location_lng: number | null;
          service_radius: number;
          operating_hours: any;
          services_offered: string[];
          pricing_info: any;
          rating: number;
          total_reviews: number;
          total_jobs_completed: number;
          is_verified: boolean;
          is_active: boolean;
          verification_documents: string[];
          license_number: string | null;
          insurance_info: any;
          images: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          business_name: string;
          service_type: 'mechanic' | 'breakdown' | 'towing' | 'detailing' | 'inspection' | 'other';
          description?: string | null;
          phone: string;
          email?: string | null;
          address?: string | null;
          location_lat?: number | null;
          location_lng?: number | null;
          service_radius?: number;
          operating_hours?: any;
          services_offered?: string[];
          pricing_info?: any;
          rating?: number;
          total_reviews?: number;
          total_jobs_completed?: number;
          is_verified?: boolean;
          is_active?: boolean;
          verification_documents?: string[];
          license_number?: string | null;
          insurance_info?: any;
          images?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          business_name?: string;
          service_type?: 'mechanic' | 'breakdown' | 'towing' | 'detailing' | 'inspection' | 'other';
          description?: string | null;
          phone?: string;
          email?: string | null;
          address?: string | null;
          location_lat?: number | null;
          location_lng?: number | null;
          service_radius?: number;
          operating_hours?: any;
          services_offered?: string[];
          pricing_info?: any;
          rating?: number;
          total_reviews?: number;
          total_jobs_completed?: number;
          is_verified?: boolean;
          is_active?: boolean;
          verification_documents?: string[];
          license_number?: string | null;
          insurance_info?: any;
          images?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      subscription_plans: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          price: number;
          billing_period: 'monthly' | 'quarterly' | 'yearly';
          features: any;
          max_listings: number;
          priority_support: boolean;
          featured_listings: boolean;
          analytics_access: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          price: number;
          billing_period: 'monthly' | 'quarterly' | 'yearly';
          features: any;
          max_listings?: number;
          priority_support?: boolean;
          featured_listings?: boolean;
          analytics_access?: boolean;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          price?: number;
          billing_period?: 'monthly' | 'quarterly' | 'yearly';
          features?: any;
          max_listings?: number;
          priority_support?: boolean;
          featured_listings?: boolean;
          analytics_access?: boolean;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan_id: string | null;
          status: 'active' | 'cancelled' | 'expired' | 'pending' | 'paused';
          start_date: string;
          end_date: string;
          auto_renew: boolean;
          payment_method: string | null;
          transaction_id: string | null;
          amount_paid: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan_id?: string | null;
          status?: 'active' | 'cancelled' | 'expired' | 'pending' | 'paused';
          start_date?: string;
          end_date: string;
          auto_renew?: boolean;
          payment_method?: string | null;
          transaction_id?: string | null;
          amount_paid?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          plan_id?: string | null;
          status?: 'active' | 'cancelled' | 'expired' | 'pending' | 'paused';
          start_date?: string;
          end_date?: string;
          auto_renew?: boolean;
          payment_method?: string | null;
          transaction_id?: string | null;
          amount_paid?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      platform_analytics: {
        Row: {
          id: string;
          date: string;
          total_views: number;
          total_unique_visitors: number;
          total_listings_viewed: number;
          total_searches: number;
          total_inquiries: number;
          total_new_users: number;
          total_new_listings: number;
          metadata: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          date: string;
          total_views?: number;
          total_unique_visitors?: number;
          total_listings_viewed?: number;
          total_searches?: number;
          total_inquiries?: number;
          total_new_users?: number;
          total_new_listings?: number;
          metadata?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          date?: string;
          total_views?: number;
          total_unique_visitors?: number;
          total_listings_viewed?: number;
          total_searches?: number;
          total_inquiries?: number;
          total_new_users?: number;
          total_new_listings?: number;
          metadata?: any;
          created_at?: string;
        };
      };
      section_analytics: {
        Row: {
          id: string;
          section_name: string;
          date: string;
          views: number;
          unique_visitors: number;
          time_spent_avg: number;
          bounce_rate: number | null;
          conversion_rate: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          section_name: string;
          date: string;
          views?: number;
          unique_visitors?: number;
          time_spent_avg?: number;
          bounce_rate?: number | null;
          conversion_rate?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          section_name?: string;
          date?: string;
          views?: number;
          unique_visitors?: number;
          time_spent_avg?: number;
          bounce_rate?: number | null;
          conversion_rate?: number | null;
          created_at?: string;
        };
      };
      item_analytics: {
        Row: {
          id: string;
          item_type: string;
          item_id: string;
          date: string;
          views: number;
          unique_visitors: number;
          inquiries: number;
          favorites: number;
          shares: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          item_type: string;
          item_id: string;
          date: string;
          views?: number;
          unique_visitors?: number;
          inquiries?: number;
          favorites?: number;
          shares?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          item_type?: string;
          item_id?: string;
          date?: string;
          views?: number;
          unique_visitors?: number;
          inquiries?: number;
          favorites?: number;
          shares?: number;
          created_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          participant_1_id: string;
          participant_2_id: string;
          reference_type: string | null;
          reference_id: string | null;
          status: 'active' | 'archived' | 'blocked';
          last_message_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          participant_1_id: string;
          participant_2_id: string;
          reference_type?: string | null;
          reference_id?: string | null;
          status?: 'active' | 'archived' | 'blocked';
          last_message_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          participant_1_id?: string;
          participant_2_id?: string;
          reference_type?: string | null;
          reference_id?: string | null;
          status?: 'active' | 'archived' | 'blocked';
          last_message_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          message_text: string;
          attachments: string[];
          is_read: boolean;
          read_at: string | null;
          is_deleted_by_sender: boolean;
          is_deleted_by_receiver: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          message_text: string;
          attachments?: string[];
          is_read?: boolean;
          read_at?: string | null;
          is_deleted_by_sender?: boolean;
          is_deleted_by_receiver?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          message_text?: string;
          attachments?: string[];
          is_read?: boolean;
          read_at?: string | null;
          is_deleted_by_sender?: boolean;
          is_deleted_by_receiver?: boolean;
          created_at?: string;
        };
      };
      payment_gateways: {
        Row: {
          id: string;
          name: string;
          type: 'mobile_money' | 'bank_transfer' | 'card' | 'crypto' | 'other';
          is_enabled: boolean;
          configuration: any;
          fees_percentage: number;
          fees_fixed: number;
          min_amount: number | null;
          max_amount: number | null;
          supported_currencies: string[];
          logo_url: string | null;
          instructions: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'mobile_money' | 'bank_transfer' | 'card' | 'crypto' | 'other';
          is_enabled?: boolean;
          configuration: any;
          fees_percentage?: number;
          fees_fixed?: number;
          min_amount?: number | null;
          max_amount?: number | null;
          supported_currencies?: string[];
          logo_url?: string | null;
          instructions?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'mobile_money' | 'bank_transfer' | 'card' | 'crypto' | 'other';
          is_enabled?: boolean;
          configuration?: any;
          fees_percentage?: number;
          fees_fixed?: number;
          min_amount?: number | null;
          max_amount?: number | null;
          supported_currencies?: string[];
          logo_url?: string | null;
          instructions?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      payment_transactions: {
        Row: {
          id: string;
          user_id: string;
          gateway_id: string | null;
          transaction_type: 'subscription' | 'listing' | 'product' | 'service' | 'other';
          reference_id: string | null;
          amount: number;
          currency: string;
          status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          payment_method: string | null;
          transaction_ref: string | null;
          payment_details: any;
          error_message: string | null;
          processed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          gateway_id?: string | null;
          transaction_type: 'subscription' | 'listing' | 'product' | 'service' | 'other';
          reference_id?: string | null;
          amount: number;
          currency?: string;
          status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          payment_method?: string | null;
          transaction_ref?: string | null;
          payment_details?: any;
          error_message?: string | null;
          processed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          gateway_id?: string | null;
          transaction_type?: 'subscription' | 'listing' | 'product' | 'service' | 'other';
          reference_id?: string | null;
          amount?: number;
          currency?: string;
          status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          payment_method?: string | null;
          transaction_ref?: string | null;
          payment_details?: any;
          error_message?: string | null;
          processed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      bank_accounts: {
        Row: {
          id: string;
          account_name: string;
          bank_name: string;
          account_number: string;
          branch_name: string | null;
          swift_code: string | null;
          currency: string;
          is_primary: boolean;
          is_active: boolean;
          instructions: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_name: string;
          bank_name: string;
          account_number: string;
          branch_name?: string | null;
          swift_code?: string | null;
          currency?: string;
          is_primary?: boolean;
          is_active?: boolean;
          instructions?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_name?: string;
          bank_name?: string;
          account_number?: string;
          branch_name?: string | null;
          swift_code?: string | null;
          currency?: string;
          is_primary?: boolean;
          is_active?: boolean;
          instructions?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      security_logs: {
        Row: {
          id: string;
          user_id: string | null;
          event_type: string;
          event_description: string;
          ip_address: string | null;
          user_agent: string | null;
          status: string | null;
          metadata: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          event_type: string;
          event_description: string;
          ip_address?: string | null;
          user_agent?: string | null;
          status?: string | null;
          metadata?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          event_type?: string;
          event_description?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          status?: string | null;
          metadata?: any;
          created_at?: string;
        };
      };
    };
  };
}